### ISSUE TITLE
Improve QuantConnect API YAML

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Documentation#2112]
To serve AI better, we need to improve QuantConnect API YAML:
- Add `required` property
- Add Example value

Example:
```yaml
    UpdateProjectRequest:
      type: object
      required: 
        - projectId
      properties:
        projectId:
          type: integer
          example: 23456789
          description: Project Id to which the file belongs.
        name:
          type: string
          description: The new name for the project.
        description:
          description: The new description for the project.
      description: Update a project name, description or parameters.
```

In this case, we already add an example for ProjectID and market it as a required. We need to mark `name` as required as well, and add an example. 
```yaml
    UpdateProjectRequest:
      type: object
      required: 
        - projectId
        - name
      properties:
        projectId:
          type: integer
          example: 23456789
          description: Project Id to which the file belongs.
        name:
          type: string
          example: "Docs Working Example"
          description: The new name for the project.
        description:
           type: string
           example: "This is a working example"
           description: The new description for the project.
      description: Update a project name, description or parameters.
```
